/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColeccionRouteImport } from './routes/coleccion'
import { Route as JugarRouteImport } from './routes/jugar'
import { Route as ApiNarradorRouteImport } from './routes/api/narrador'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColeccionRoute = ColeccionRouteImport.update({
  id: '/coleccion',
  path: '/coleccion',
  getParentRoute: () => rootRouteImport,
} as any)
const JugarRoute = JugarRouteImport.update({
  id: '/jugar',
  path: '/jugar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNarradorRoute = ApiNarradorRouteImport.update({
  id: '/api/narrador',
  path: '/api/narrador',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coleccion': typeof ColeccionRoute
  '/jugar': typeof JugarRoute
  '/api/narrador': typeof ApiNarradorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coleccion': typeof ColeccionRoute
  '/jugar': typeof JugarRoute
  '/api/narrador': typeof ApiNarradorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coleccion': typeof ColeccionRoute
  '/jugar': typeof JugarRoute
  '/api/narrador': typeof ApiNarradorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/coleccion' | '/jugar' | '/api/narrador'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/coleccion' | '/jugar' | '/api/narrador'
  id: '__root__' | '/' | '/coleccion' | '/jugar' | '/api/narrador'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColeccionRoute: typeof ColeccionRoute
  JugarRoute: typeof JugarRoute
  ApiNarradorRoute: typeof ApiNarradorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coleccion': {
      id: '/coleccion'
      path: '/coleccion'
      fullPath: '/coleccion'
      preLoaderRoute: typeof ColeccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jugar': {
      id: '/jugar'
      path: '/jugar'
      fullPath: '/jugar'
      preLoaderRoute: typeof JugarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/narrador': {
      id: '/api/narrador'
      path: '/api/narrador'
      fullPath: '/api/narrador'
      preLoaderRoute: typeof ApiNarradorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColeccionRoute: ColeccionRoute,
  JugarRoute: JugarRoute,
  ApiNarradorRoute: ApiNarradorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
