/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ColeccionRouteImport } from './routes/coleccion'
import { Route as JugarRouteImport } from './routes/jugar'
import { Route as PrivacidadRouteImport } from './routes/privacidad'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColeccionRoute = ColeccionRouteImport.update({
  id: '/coleccion',
  path: '/coleccion',
  getParentRoute: () => rootRouteImport,
} as any)
const JugarRoute = JugarRouteImport.update({
  id: '/jugar',
  path: '/jugar',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coleccion': typeof ColeccionRoute
  '/jugar': typeof JugarRoute
  '/privacidad': typeof PrivacidadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coleccion': typeof ColeccionRoute
  '/jugar': typeof JugarRoute
  '/privacidad': typeof PrivacidadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coleccion': typeof ColeccionRoute
  '/jugar': typeof JugarRoute
  '/privacidad': typeof PrivacidadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/coleccion' | '/jugar' | '/privacidad'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/coleccion' | '/jugar' | '/privacidad'
  id: '__root__' | '/' | '/coleccion' | '/jugar' | '/privacidad'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ColeccionRoute: typeof ColeccionRoute
  JugarRoute: typeof JugarRoute
  PrivacidadRoute: typeof PrivacidadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coleccion': {
      id: '/coleccion'
      path: '/coleccion'
      fullPath: '/coleccion'
      preLoaderRoute: typeof ColeccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jugar': {
      id: '/jugar'
      path: '/jugar'
      fullPath: '/jugar'
      preLoaderRoute: typeof JugarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ColeccionRoute: ColeccionRoute,
  JugarRoute: JugarRoute,
  PrivacidadRoute: PrivacidadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
